### PR TITLE
Full support for Handlebars

### LINKED ISSUE #25: Use HTML grammar
Looks like you have copypasta'd the language html grammar, including all the snippets. You can include grammars rather than duplicating them. See the [erb definition](https://github.com/atom/language-ruby/blob/ed32555f7e08584aab5a21d144fdcfc14871c0d0/grammars/html%20(ruby%20-%20erb).cson#L49) for an example.

### LINKED ISSUE #26: Remove text.html snippets
The snippets are scoped to `text.html` which applies to every html-related language: html, erb, etc. They will be unnecessary soon with the inclusion of autocomplete-html in core.

### PR DESCRIPTION
**Pull request by taylon**
Hey @Sneagan,

This is pretty much a rewrite of the package. It fixes literally all the issues currently opened, greatly improves the syntax highlighting and add snippets for Handlebars (which didn't existed before).

* Fix #25, #24, #17, #15, #14, #13, #12, #9, #5: Handlebars grammar was greatly improved by providing custom highlighting for each kind of expression and including the HTML grammar instead of pasting it into the package.

* Support for code folding for Handlebars blocks

* Fix #26: Snippets for Handlebars were added. Before it would only include HTML snippets which are now unnecessary since we are including the HTML grammar, so now we have both specific Handlebars snippets and all the HTML snippets that we use to have.

* Improved README file.

* I have added a bunch of tests, coffeelint and a travis.yml file, so I recommend you to setup a Travis job for it =D (instructions here http://docs.travis-ci.com/user/getting-started/#Step-two%3A-Activate-GitHub-Webhook)

* I also recommend you to change the LICENSE to include your name. A list of contributors on the README file would also be nice.

* Also, I think it should be a major release.

This is nice because Atom as a whole was lacking Handlebars support, there was no package with decent support for Handlebars, now we have =D

### CODE REVIEW

**Comment by Sneagan** [comment]
This is so awesome! I'll review it ASAP!

**Comment by nickpfisterer** [comment]
@taylon: I got so excited about this I had to test your fork while I wait for Sneagan to merge it. I tested it with Atom v0.199.0 and, unfortunately, the syntax highlighting is still totally broken for me. :sob: Any idea what might be going wrong? The lack of Handlebars support is absolutely killing me, so I'll try to help out with this as best I can!

**Comment by taylon** [comment]
Hey nick, that is wierd ill check it out as soon as i get home later today, are you on MacOS?

**Comment by nickpfisterer** [comment]
I'm on Windows 10 Technical Preview. @taylon Here's an example of what I'm experiencing:

atom-handlebars syntax highlighting example

As you can see, I'm getting very spotty highlighting. Something is not right with the scopes; I just wish I knew what. I took a look at your code and the scopes look right to me, so I'm at a loss for where to go next.

**Comment by taylon** [comment]
Hey @nickpfisterer 

It seems to be a problem with the language-html package (https://github.com/atom/language-html/issues/62), probably due to the many recent changes to it.
Since it is also breaking other packages I hope that the guys fix it and then atom-handlebars should just work as expected.

I'll track the issues with language-html package, as soon as we get an update on that I'll let you guys know.

**Comment by nickpfisterer** [comment]
@taylon Thanks for the update. Hopefully the issues with language-html can get resolved soon. :)

**Comment by taylon** [comment]
Hey @nickpfisterer the issue was solved in language-html (https://github.com/atom/language-html/commit/3a9bedebfa26d916488df45e99ce536b7abdfff4) =D
Can you confirm if the pull request works for you now? It's working great for me

@Sneagan any idea on when you could accept this pull request?

**Comment by dbooom** [comment]
It seems that we have to cover "triple-stash" expressions as well. They're currently not highlighted

```
{{{expression}}}
```

screen shot 2015-05-28 at 22 54 51

**Comment by mikegleasonjr** [comment]
:+1:

**Comment by Benjamski** [comment]
Is anyone else having the issue where using the comment key binding in HTML results in handlbars comments instead? I haven't quite been able to figure out how to change that. Is it a built in atom setting? Or a package I need to change?

**Pull request merged**
